/***********************************************************************************************   
AUTOR		:	rbendezuv
PROPOSITO	:	Creación de tablas de negocio
CREADO 		:	31/05/2024
ALCANCE		:	Proyecto conexiones base de datos
   
************************************************************************************************   
ID	  AUTOR	          FECHA	     	PROPOSITO                                                               
--    --------------	------------	------------------------------------------------------------   
@1    rbendezuv       31/05/2024    Creación de tablas de negocio
************************************************************************************************/ 
DO $$
BEGIN

DROP TABLE IF EXISTS "BDCONEXIONES".""
CREATE TABLE IF NOT EXISTS "BDCONEXIONES"."MAE_USUARIOS" (
  "N_USUARIO" INT2 NOT NULL,
  "X_USUARIO" VARCHAR(30) NOT NULL,
  "X_PASSWORD" VARCHAR(15) NOT NULL,
  "L_ACTIVO" VARCHAR(1) NOT NULL DEFAULT '1',
  "F_REGISTRO" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "F_AUD" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "B_AUD" VARCHAR(1) NOT NULL DEFAULT 'I',
  "X_AUD_UID" VARCHAR(30) DEFAULT (CURRENT_USER),
  "X_AUD_UIDRED" VARCHAR(30),
  "X_AUD_PC" VARCHAR(30),
  "X_AUD_IP" VARCHAR(40),
  "X_AUD_MCADDR" VARCHAR(17),
  PRIMARY KEY ("N_USUARIO")
) TABLESPACE "TBS_BDCONEXIONES_MAE";

DROP TABLE IF EXISTS "BDCONEXIONES".""
CREATE TABLE IF NOT EXISTS "BDCONEXIONES"."MAE_ROLES" (
  "N_ROL" INT4 NOT NULL,
  "X_NOMBRE_ROL" VARCHAR(15) NOT NULL,
  "L_ACTIVO" VARCHAR(1) NOT NULL DEFAULT '1',
  "F_REGISTRO" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "F_AUD" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "B_AUD" VARCHAR(1) NOT NULL DEFAULT 'I',
  "X_AUD_UID" VARCHAR(30) DEFAULT (CURRENT_USER),
  "X_AUD_UIDRED" VARCHAR(30),
  "X_AUD_PC" VARCHAR(30),
  "X_AUD_IP" VARCHAR(40),
  "X_AUD_MCADDR" VARCHAR(17)
) TABLESPACE "TBS_BDCONEXIONES_MAE";

DROP TABLE IF EXISTS "BDCONEXIONES".""
CREATE TABLE IF NOT EXISTS "BDCONEXIONES"."MAE_ROL_USUARIOS" (
  "N_ROL" INT4 NOT NULL,
  "N_USUARIO" INT4 NOT NULL,
  "L_ACTIVO" VARCHAR(1) NOT NULL DEFAULT '1',
  "F_REGISTRO" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "F_AUD" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "B_AUD" VARCHAR(1) NOT NULL DEFAULT 'I',
  "X_AUD_UID" VARCHAR(30) DEFAULT (CURRENT_USER),
  "X_AUD_UIDRED" VARCHAR(30),
  "X_AUD_PC" VARCHAR(30),
  "X_AUD_IP" VARCHAR(40),
  "X_AUD_MCADDR" VARCHAR(17),
  PRIMARY KEY ("N_ROL", "N_USUARIO")
) TABLESPACE "TBS_BDCONEXIONES_MAE";


DROP TABLE IF EXISTS "BDCONEXIONES".""
CREATE TABLE IF NOT EXISTS "MAE_DISTRITO_JUDICIALES" (
  "C_DISTRITO" VARCHAR(3) UNIQUE PRIMARY KEY,
  "X_NOMBRE" VARCHAR(80) NOT NULL,
  "L_ACTIVO" "CHAR (1)" NOT NULL DEFAULT '1',
  "N_USUARIO_OPERACION" NUMERIC(7,0),
  "F_AUD" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "B_AUD" "CHAR (1)" NOT NULL DEFAULT 'I',
  "X_AUD_UID" VARCHAR(30) DEFAULT (CURRENT_USER),
  "X_AUD_UIDRED" VARCHAR(30),
  "X_AUD_PC" VARCHAR(30),
  "X_AUD_IP" VARCHAR(15),
  "X_AUD_MCADDR" VARCHAR(17)
)TABLESPACE "TBS_BDCONEXIONES_MAE";

DROP TABLE IF EXISTS "BDCONEXIONES".""
CREATE TABLE IF NOT EXISTS "MAE_SEDES" (
  "C_SEDE" VARCHAR(4) UNIQUE PRIMARY KEY,
  "C_DISTRITO" VARCHAR(3) NOT NULL,
  "X_NOMBRE" VARCHAR(120) NOT NULL,
  "L_ACTIVO" "CHAR (1)" NOT NULL DEFAULT '1',
  "N_USUARIO_OPERACION" NUMERIC(7,0),
  "F_AUD" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "B_AUD" "CHAR (1)" NOT NULL DEFAULT 'I',
  "X_AUD_UID" VARCHAR(30) DEFAULT (CURRENT_USER),
  "X_AUD_UIDRED" VARCHAR(30),
  "X_AUD_PC" VARCHAR(30),
  "X_AUD_IP" VARCHAR(15),
  "X_AUD_MCADDR" VARCHAR(17)
)TABLESPACE "TBS_BDCONEXIONES_MAE";

DROP TABLE IF EXISTS "BDCONEXIONES".""
CREATE TABLE IF NOT EXISTS "MAE_ESQUEMAS" (
  "N_ID_ESQUEMA" NUMERIC(7,0) PRIMARY KEY,
  "X_ESQUEMA" VARCHAR(80),
  "L_ACTIVO" "CHAR (1)" NOT NULL DEFAULT '1',
  "N_USUARIO_OPERACION" NUMERIC(7,0),
  "F_AUD" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "B_AUD" "CHAR (1)" NOT NULL DEFAULT 'I',
  "X_AUD_UID" VARCHAR(30) DEFAULT (CURRENT_USER),
  "X_AUD_UIDRED" VARCHAR(30),
  "X_AUD_PC" VARCHAR(30),
  "X_AUD_IP" VARCHAR(15),
  "X_AUD_MCADDR" VARCHAR(17)
)TABLESPACE "TBS_BDCONEXIONES_MAE";

DROP TABLE IF EXISTS "BDCONEXIONES".""
CREATE TABLE IF NOT EXISTS "MAE_BASEDATOS" (
  "N_ID_BASE_DATOS" NUMERIC(7,0) PRIMARY KEY,
  "C_DISTRITO" VARCHAR(3),
  "C_SEDE" VARCHAR(4),
  "N_ID_ESQUEMA" NUMERIC(7,0),
  "X_EDICION" VARCHAR(20),
  "X_NOMBRE" VARCHAR(100),
  "X_DESCRIPCION" VARCHAR(250),
  "X_IP_SERVIDOR" VARCHAR(45),
  "X_PUERTO" VARCHAR(10),
  "X_INSTANCIA" VARCHAR(50),
  "L_ES_PRINCIPAL" "CHAR (1)" NOT NULL DEFAULT '1',
  "F_REGISTRO" TIMESTAMP,
  "L_ACTIVO" "CHAR (1)" NOT NULL DEFAULT '1',
  "X_ESQUEMA" VARCHAR(20),
  "N_ID_BD_ESTADISTICA" INT,
  "X_DRIVER" VARCHAR(80),
  "X_URL" VARCHAR(80),
  "N_USUARIO_OPERACION" NUMERIC(7,0),
  "F_AUD" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "B_AUD" "CHAR (1)" NOT NULL DEFAULT 'I',
  "X_AUD_UID" VARCHAR(30) DEFAULT (CURRENT_USER),
  "X_AUD_UIDRED" VARCHAR(30),
  "X_AUD_PC" VARCHAR(30),
  "X_AUD_IP" VARCHAR(15),
  "X_AUD_MCADDR" VARCHAR(17)
)TABLESPACE "TBS_BDCONEXIONES_MAE";

DROP TABLE IF EXISTS "BDCONEXIONES".""
CREATE TABLE IF NOT EXISTS "MOV_CONEXIONES" (
  "N_ID_TIPO_CONEXION" NUMERIC(5,0),
  "N_ID_BASE_DATOS" NUMERIC(7,0),
  "N_ID_COMPONENTE" NUMERIC(5,0),
  "X_NOMBRE" VARCHAR(50),
  "X_JNDI" VARCHAR(100),
  "X_USUARIO" VARCHAR(50),
  "F_REGISTRO" TIMESTAMP,
  "L_ACTIVO" "CHAR (1)" NOT NULL DEFAULT '1',
  "X_CLAVE" VARCHAR(200),
  "N_USUARIO_OPERACION" NUMERIC(7,0),
  "F_AUD" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "B_AUD" "CHAR (1)" NOT NULL DEFAULT 'I',
  "X_AUD_UID" VARCHAR(30) DEFAULT (CURRENT_USER),
  "X_AUD_UIDRED" VARCHAR(30),
  "X_AUD_PC" VARCHAR(30),
  "X_AUD_IP" VARCHAR(15),
  "X_AUD_MCADDR" VARCHAR(17),
  PRIMARY KEY ("N_ID_TIPO_CONEXION", "N_ID_BASE_DATOS", "N_ID_COMPONENTE")
)TABLESPACE "TBS_BDCONEXIONES_MOV";

DROP TABLE IF EXISTS "BDCONEXIONES".""
CREATE TABLE IF NOT EXISTS "MAE_TIPO_CONEXIONES" (
  "N_ID_TIPO_CONEXION" NUMERIC(5,0) PRIMARY KEY,
  "X_NOMBRE" VARCHAR(50),
  "L_ACTIVO" "CHAR (1)" NOT NULL DEFAULT '1',
  "N_USUARIO_OPERACION" NUMERIC(7,0),
  "F_AUD" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "B_AUD" "CHAR (1)" NOT NULL DEFAULT 'I',
  "X_AUD_UID" VARCHAR(30) DEFAULT (CURRENT_USER),
  "X_AUD_UIDRED" VARCHAR(30),
  "X_AUD_PC" VARCHAR(30),
  "X_AUD_IP" VARCHAR(15),
  "X_AUD_MCADDR" VARCHAR(17)
)TABLESPACE "TBS_BDCONEXIONES_MAE";

DROP TABLE IF EXISTS "BDCONEXIONES".""
CREATE TABLE IF NOT EXISTS "MAE_SISTEMAS" (
  "N_ID_SISTEMA" NUMERIC(5,0) PRIMARY KEY,
  "N_ID_TIPO_SISTEMA" NUMERIC(5,0),
  "X_NOMBRE" VARCHAR(50),
  "X_DESCRIPCION" VARCHAR(150),
  "L_ACTIVO" "CHAR (1)" NOT NULL DEFAULT '1',
  "N_USUARIO_OPERACION" NUMERIC(7,0),
  "F_AUD" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "B_AUD" "CHAR (1)" NOT NULL DEFAULT 'I',
  "X_AUD_UID" VARCHAR(30) DEFAULT (CURRENT_USER),
  "X_AUD_UIDRED" VARCHAR(30),
  "X_AUD_PC" VARCHAR(30),
  "X_AUD_IP" VARCHAR(15),
  "X_AUD_MCADDR" VARCHAR(17)
)TABLESPACE "TBS_BDCONEXIONES_MAE";

DROP TABLE IF EXISTS "BDCONEXIONES".""
CREATE TABLE IF NOT EXISTS "MAE_COMPONENTES" (
  "N_ID_COMPONENTE" NUMERIC(5,0) PRIMARY KEY,
  "N_ID_SISTEMA" NUMERIC(5,0),
  "X_NOMBRE" VARCHAR(50),
  "X_DESCRIPCION" VARCHAR(150),
  "L_ACTIVO" "CHAR (1)" NOT NULL DEFAULT '1',
  "N_USUARIO_OPERACION" NUMERIC(7,0),
  "F_AUD" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "B_AUD" "CHAR (1)" NOT NULL DEFAULT 'I',
  "X_AUD_UID" VARCHAR(30) DEFAULT (CURRENT_USER),
  "X_AUD_UIDRED" VARCHAR(30),
  "X_AUD_PC" VARCHAR(30),
  "X_AUD_IP" VARCHAR(15),
  "X_AUD_MCADDR" VARCHAR(17)
)TABLESPACE "TBS_BDCONEXIONES_MAE";

DROP TABLE IF EXISTS "BDCONEXIONES".""
CREATE TABLE IF NOT EXISTS "MAE_TIPO_SISTEMAS" (
  "N_ID_TIPO_SISTEMA" NUMERIC(5,0) PRIMARY KEY,
  "X_NOMBRE" VARCHAR(50),
  "L_ACTIVO" "CHAR (1)" NOT NULL DEFAULT '1',
  "N_USUARIO_OPERACION" NUMERIC(7,0),
  "F_AUD" TIMESTAMP NOT NULL DEFAULT (LOCALTIMESTAMP),
  "B_AUD" "CHAR (1)" NOT NULL DEFAULT 'I',
  "X_AUD_UID" VARCHAR(30) DEFAULT (CURRENT_USER),
  "X_AUD_UIDRED" VARCHAR(30),
  "X_AUD_PC" VARCHAR(30),
  "X_AUD_IP" VARCHAR(15),
  "X_AUD_MCADDR" VARCHAR(17)
)TABLESPACE "TBS_BDCONEXIONES_MAE";

ALTER TABLE "MAE_SEDES" ADD FOREIGN KEY ("C_DISTRITO") REFERENCES "MAE_DISTRITO_JUDICIALES" ("C_DISTRITO");

ALTER TABLE "MAE_BASEDATOS" ADD FOREIGN KEY ("N_ID_ESQUEMA") REFERENCES "MAE_ESQUEMAS" ("N_ID_ESQUEMA");

ALTER TABLE "MAE_BASEDATOS" ADD FOREIGN KEY ("C_SEDE") REFERENCES "MAE_SEDES" ("C_SEDE");

ALTER TABLE "MAE_CONEXIONES" ADD FOREIGN KEY ("N_ID_BASE_DATOS") REFERENCES "MAE_BASEDATOS" ("N_ID_BASE_DATOS");

ALTER TABLE "MAE_CONEXIONES" ADD FOREIGN KEY ("N_ID_TIPO_CONEXION") REFERENCES "MAE_TIPO_CONEXIONES" ("N_ID_TIPO_CONEXION");

ALTER TABLE "MAE_CONEXIONES" ADD FOREIGN KEY ("N_ID_COMPONENTE") REFERENCES "MAE_COMPONENTES" ("N_ID_COMPONENTE");

ALTER TABLE "MAE_COMPONENTES" ADD FOREIGN KEY ("N_ID_SISTEMA") REFERENCES "MAE_SISTEMAS" ("N_ID_SISTEMA");

ALTER TABLE "MAE_SISTEMAS" ADD FOREIGN KEY ("N_ID_TIPO_SISTEMA") REFERENCES "MAE_TIPO_SISTEMAS" ("N_ID_TIPO_SISTEMA");

-- Mensajes de creación de tablas
    RAISE NOTICE 'Todas las tablas han sido creadas exitosamente en el esquema serviciosexternos.';

EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION 'Error al crear las tablas: %', SQLERRM;
END $$;